### ISSUE TITLE
nick_complete_wrapper: åäö offsets the prefix

### ISSUE THREAD

**Issue by ywecur** [tomoe-mami/weechat-scripts#3]
If the text preceding the name contains `å`, `ä` or `ö`  the prefix is offset one step per character included.

For example: With the prefix set to `@` the message: `öland username` + `<TAB>` will yield `öland u@sername`

The message: `ööland username` + `<TAB>` will yield `ööland us@ername`

**Comment by tomoe-mami** [comment]
Thanks for the report.

This was because I assumed the `position_replace` variable (the start position of completed nick) from the API was utf8 pos. Turns out it's in bytes. Well... [the API doesn't explain anything about what any of these variables mean][1]. So when the script told weechat to insert a char in that position, it will be at the wrong place because the `position_replace` value is larger than the actual position on screen when there's multibyte character.

Can you try again with the latest commit?

[1]: https://weechat.org/doc/api#hdata_completion

**Comment by ywecur** [comment]
Fixed in f174031
